/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Ema
 */
public class ConfiguracionAvanzada extends javax.swing.JPanel {

    /**
     * Creates new form ConfiguracionAvanzada
     */
    JDesktopPane desktop;
    VistaConsultorio cons;
    menu menu;

    public ConfiguracionAvanzada(JDesktopPane jk, menu menu) {
        initComponents();
        desktop = jk;
        this.menu = menu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbabrirconsultorio = new javax.swing.JButton();
        jbsalir = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        jbabrirconsultorio.setBackground(new java.awt.Color(0, 204, 204));
        jbabrirconsultorio.setText("Abrir Consultorio");
        jbabrirconsultorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbabrirconsultorioActionPerformed(evt);
            }
        });

        jbsalir.setBackground(new java.awt.Color(255, 102, 102));
        jbsalir.setText("Salir");
        jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moderno", "Clásico", "Antiguo", "Windows", "Sistema Operativo" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Aplicar tema");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 416, Short.MAX_VALUE)
                        .addComponent(jbabrirconsultorio)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbabrirconsultorio)
                    .addComponent(jbsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed

        this.setVisible(false);
        this.setEnabled(false);
        menu.activarTodosLosBotones();


    }//GEN-LAST:event_jbsalirActionPerformed

    private void jbabrirconsultorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbabrirconsultorioActionPerformed

    }//GEN-LAST:event_jbabrirconsultorioActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String TemSeleccionafo = (String) jComboBox1.getSelectedItem();
        String clase = "";

        try {
            switch (TemSeleccionafo) {
                case "Moderno":
                    clase = "javax.swing.plaf.nimbus.NimbusLookAndFeel";
                    break;
                case "Clásico":
                    clase = UIManager.getCrossPlatformLookAndFeelClassName();
                    break;
                case "Antiguo":
                    clase = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";
                    break;
                case "Windows":
                    clase = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
                    break;
                case "Sistema Operativo":
                    clase = UIManager.getSystemLookAndFeelClassName();
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Tema no reconocido.", "Error", JOptionPane.ERROR_MESSAGE);
return;
            }
            
            UIManager.setLookAndFeel(clase);
            SwingUtilities.updateComponentTreeUI(this.menu);
            SwingUtilities.updateComponentTreeUI(this);
            
            JOptionPane.showMessageDialog(this, "Tema cambiado a " + TemSeleccionafo, "Cambio Exitoso", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException e) {
            JOptionPane.showMessageDialog(this, 
            "El tema seleccionado no es compatible o hubo un error: " + e.getMessage(), 
            "Error de Tema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JButton jbabrirconsultorio;
    private javax.swing.JButton jbsalir;
    // End of variables declaration//GEN-END:variables

    public JDesktopPane getDesktop() {
        return desktop;
    }

    public void setDesktop(JDesktopPane desktop) {
        this.desktop = desktop;
    }

    public VistaConsultorio getCons() {
        return cons;
    }

    public void setCons(VistaConsultorio cons) {
        this.cons = cons;
    }

    public JButton getJbabrirconsultorio() {
        return jbabrirconsultorio;
    }

    public void setJbabrirconsultorio(JButton jbabrirconsultorio) {
        this.jbabrirconsultorio = jbabrirconsultorio;
    }

    public JButton getJbsalir() {
        return jbsalir;
    }

    public void setJbsalir(JButton jbsalir) {
        this.jbsalir = jbsalir;
    }

}
