/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;

/**
 *
 * @author Ema
 */
public class ConfiguracionAvanzada extends javax.swing.JPanel {

    /**
     * Creates new form ConfiguracionAvanzada
     */
    JDesktopPane desktop;
    VistaConsultorio cons;
    menu menu;
    
    public ConfiguracionAvanzada(JDesktopPane jk, menu menu) {
    initComponents();
    desktop = jk;
    this.menu = menu;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbabrirconsultorio = new javax.swing.JButton();
        jbsalir = new javax.swing.JButton();

        jbabrirconsultorio.setText("Abrir Consultorio");
        jbabrirconsultorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbabrirconsultorioActionPerformed(evt);
            }
        });

        jbsalir.setText("Salir");
        jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbsalir)
                    .addComponent(jbabrirconsultorio))
                .addContainerGap(553, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jbabrirconsultorio)
                .addGap(126, 126, 126)
                .addComponent(jbsalir)
                .addContainerGap(191, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbabrirconsultorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbabrirconsultorioActionPerformed
    
   
    }//GEN-LAST:event_jbabrirconsultorioActionPerformed

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed
      
       
      this.setVisible(false);
    this.setEnabled(false);
    menu.activarTodosLosBotones();
    }//GEN-LAST:event_jbsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbabrirconsultorio;
    private javax.swing.JButton jbsalir;
    // End of variables declaration//GEN-END:variables

    public JDesktopPane getDesktop() {
        return desktop;
    }

    public void setDesktop(JDesktopPane desktop) {
        this.desktop = desktop;
    }

    public VistaConsultorio getCons() {
        return cons;
    }

    public void setCons(VistaConsultorio cons) {
        this.cons = cons;
    }

    public JButton getJbabrirconsultorio() {
        return jbabrirconsultorio;
    }

    public void setJbabrirconsultorio(JButton jbabrirconsultorio) {
        this.jbabrirconsultorio = jbabrirconsultorio;
    }

    public JButton getJbsalir() {
        return jbsalir;
    }

    public void setJbsalir(JButton jbsalir) {
        this.jbsalir = jbsalir;
    }


}
