/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Instalacion;
import Modelo.Tratamiento;
import Persistencia.InstalacionData;
import java.sql.Time;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author angel
 */
    public class VistaInstalacion extends javax.swing.JInternalFrame {
    private InstalacionData instalacionData = new InstalacionData();
    private DefaultTableModel modeloTabla;
    menu menu;
    
    /**
     * Creates new form VistaInstalacion
     */
    public VistaInstalacion(menu menu) {
        initComponents();
        configurarTabla();
        actulizarTabla();
        configurarSeleccionTabla();
        this.menu = menu;
    }
    
      
     private Instalacion obtenerInstalacion(){
 
    int codInstal = 0;
    double costo = 0;

    try {
        if (txtCodins.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "El Codigo es obligatorio", "Faltan Datos", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        
 
        codInstal = Integer.parseInt(txtCodins.getText().trim());


        if (!txtCostoins.getText().trim().isEmpty()) {
            costo = Double.parseDouble(txtCostoins.getText().trim());
        }

        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El codigo y el costo deben ser números validos", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        return null;
    }
    
    Instalacion nuevaInstalacion = new Instalacion();

    nuevaInstalacion.setCodInstal(codInstal);
    nuevaInstalacion.setNombre(txtNombreins.getText().trim());
    nuevaInstalacion.setDetalleUso(txtDetalleins.getText().trim());
    nuevaInstalacion.setPrecio30min(costo);
    boolean estadoActivo = chkEstadoins.isSelected();
    nuevaInstalacion.setEstado(estadoActivo);
    

    return nuevaInstalacion;
     }
     
     
private void configurarTabla(){
    String[] Titulos = {"codInstalacion", "Nombre", "detalle","costo","estado"};
    modeloTabla = new DefaultTableModel(Titulos, 0);
    jTable1.setModel(modeloTabla);
}

    
    private void Limpiar(){
        txtCodins.setText("");
        txtNombreins.setText("");
        txtDetalleins.setText("");
        txtCostoins.setText("");
        chkEstadoins.setSelected(false);
    }
    
     private void actulizarTabla(){
       
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel(); 
    modelo.setRowCount(0); 
    List<Instalacion> instalaciones = instalacionData.listarInstalaciones();
    System.out.println("Instalaciones cargadas de DB: " + instalaciones.size());
  
    for (Instalacion t : instalaciones) {

        modelo.addRow(new Object[]{
            t.getCodInstal(),
            t.getNombre(),
            t.getDetalleUso(),
            t.getPrecio30min(),
            t.isEstado()
        });
    }
}
     
      private void configurarSeleccionTabla() {

    jTable1.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            cargarCamposDesdeTabla();
        }
    });
}
    
    private void cargarCamposDesdeTabla() {
    int filaSeleccionada = jTable1.getSelectedRow();
    
    if (filaSeleccionada >= 0) {
        // Obtenemos el modelo de la tabla para acceder a los valores
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        
        // 1. Cargar el Código (Columna 0)
        String codInstal = modelo.getValueAt(filaSeleccionada, 0).toString();
        txtCodins.setText(codInstal);
        

        txtNombreins.setText(modelo.getValueAt(filaSeleccionada, 1).toString());
        txtDetalleins.setText(modelo.getValueAt(filaSeleccionada, 2).toString());
        
        // 3. Cargar Costo (Columna 5)
        txtCostoins.setText(modelo.getValueAt(filaSeleccionada, 3).toString());

        // 4. Cargar Estado (Columna 6)
        boolean estado = (Boolean) modelo.getValueAt(filaSeleccionada, 4);
        chkEstadoins.setSelected(estado);
        
        // 6. Deshabilitar la edición del código (ya que es la clave)
        txtCodins.setEnabled(false);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        labelIns1 = new javax.swing.JLabel();
        labelins2 = new javax.swing.JLabel();
        labelins3 = new javax.swing.JLabel();
        labelins5 = new javax.swing.JLabel();
        chkEstadoins = new javax.swing.JCheckBox();
        labelins7 = new javax.swing.JLabel();
        txtCodins = new javax.swing.JTextField();
        txtNombreins = new javax.swing.JTextField();
        txtDetalleins = new javax.swing.JTextField();
        txtCostoins = new javax.swing.JTextField();
        labelTrat10 = new javax.swing.JLabel();
        checkBaja = new javax.swing.JRadioButton();
        checkAlta = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        labelIns1.setText("Cod. Instalacion");

        labelins2.setText("Nombre:");

        labelins3.setText("Detalle de uso");

        labelins5.setText("Costo");

        chkEstadoins.setMaximumSize(new java.awt.Dimension(30, 30));
        chkEstadoins.setMinimumSize(new java.awt.Dimension(30, 30));
        chkEstadoins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEstadoinsActionPerformed(evt);
            }
        });

        labelins7.setText("Estado");

        txtCodins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodinsActionPerformed(evt);
            }
        });

        buttonGroup1.add(checkBaja);
        checkBaja.setText("BajaLogica");

        buttonGroup1.add(checkAlta);
        checkAlta.setText("AltaLogica");

        jButton5.setText("Dar de Baja/Alta");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTrat10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelins7)
                        .addComponent(labelins5)
                        .addComponent(labelins3)
                        .addComponent(labelins2)
                        .addComponent(labelIns1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCostoins, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreins, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDetalleins, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(chkEstadoins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCodins, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(478, 478, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkAlta)
                        .addGap(36, 36, 36)
                        .addComponent(jButton5)
                        .addGap(40, 40, 40)
                        .addComponent(checkBaja)
                        .addGap(31, 31, 31))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(btnModificar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIns1)
                    .addComponent(txtCodins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelins2)
                    .addComponent(txtNombreins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelins3)
                    .addComponent(txtDetalleins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelins5)
                    .addComponent(txtCostoins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkEstadoins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelins7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(labelTrat10)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkBaja)
                            .addComponent(jButton5)
                            .addComponent(checkAlta))
                        .addGap(64, 64, 64))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton4.setText("SALIR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Detalle", "Costo", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(381, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodinsActionPerformed

    private void chkEstadoinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEstadoinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEstadoinsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int filaSElec = jTable1.getSelectedRow();

        if (filaSElec == -1) {
            JOptionPane.showMessageDialog(this, "Se tiene q elegir una instalacion de la tabla para eliminarla", "Requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Object valorCLiCod = modeloTabla.getValueAt(filaSElec, 0);

        if (valorCLiCod == null) {
            JOptionPane.showMessageDialog(this, "No tiene codigo de instalacion valido esta fila", "Eror de datos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {

            int codInstal = (int) valorCLiCod;

            int confrimacion = JOptionPane.showConfirmDialog(this,
                "Seguro de eliminar la instalacion?", "Confirmar elimanar", JOptionPane.YES_NO_OPTION);

            if (confrimacion == JOptionPane.YES_OPTION) {

                instalacionData.borrarInstalacion(codInstal);
                JOptionPane.showMessageDialog(this,"Instalacion dada de baja","Dada de baja existosa", JOptionPane.INFORMATION_MESSAGE);

                Limpiar();
                actulizarTabla();

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al dar de baja Detalle:" + e.getMessage(), "Error" , JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Instalacion nuevaInstalacion = obtenerInstalacion();

        if (nuevaInstalacion == null) {
            return;
        }

        int codigoIngresado = nuevaInstalacion.getCodInstal();

        try {

            if (instalacionData.existeInstalacion(codigoIngresado)){

                JOptionPane.showMessageDialog(this,
                    "️ El codigo de Instalacion " + codigoIngresado + " ya existe. No se puede guardar",
                    "Código Duplicado",
                    JOptionPane.WARNING_MESSAGE);

            } else {

                instalacionData.guardarInstalacion(nuevaInstalacion);

                JOptionPane.showMessageDialog(this,
                    "Instalacion: " + nuevaInstalacion.getNombre() + " guardada correctamente",
                    "Guardado Exitoso",
                    JOptionPane.INFORMATION_MESSAGE);

                //Limpiar();
                //actulizarTabla();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                " Error al intentar guardar el tratamiento: " + e.getMessage(),
                "Error al Guardar",
                JOptionPane.ERROR_MESSAGE);
        }
        
        Limpiar();
        actulizarTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       this.setEnabled(false);
       this.setVisible(false);
        menu.activarTodosLosBotones();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int filaSelec = jTable1.getSelectedRow();
        try {
            if (filaSelec == -1) {
                JOptionPane.showMessageDialog(this,"Debe elegir una instalacion de la tabla para dar de baja", "Requierido" ,JOptionPane.WARNING_MESSAGE);
                return;
            }
            Object valorCod = modeloTabla.getValueAt(filaSelec, 0);

            int codigoInstalacion = (int)valorCod;

            if (checkAlta.isSelected()) {
                instalacionData.altaLogica(codigoInstalacion);
                JOptionPane.showMessageDialog(this, "Instalacion dada de ALTA correctamente.", "Estado Cambiado", JOptionPane.INFORMATION_MESSAGE);

            } else if (checkBaja.isSelected()) {
                int confirmacion = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro de que desea dar de BAJA LÓGICA a la instalacion con Codigo: " + codigoInstalacion + "?",
                    "Confirmar Baja", JOptionPane.YES_NO_OPTION);

                if (confirmacion == JOptionPane.YES_OPTION) {
                    instalacionData.bajaLogica(codigoInstalacion);
                    JOptionPane.showMessageDialog(this, "Instalacion dada de BAJA correctamente.", "Estado Cambiado", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    return;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Debe seleccionar Alta o Baja.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            actulizarTabla();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe cargar el Codigo de Instalacion en el primer campo para cambiar su estado.", "Error", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cambiar el estado: " + ex.getMessage(), "Error de BD", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
          if (jTable1.getSelectedRow() == -1) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar una Instalacion para modificar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    Instalacion instalacionModificada = obtenerInstalacion();
    
    if (instalacionModificada != null) {
        try {
  
            instalacionData.actualizarInstalacion(instalacionModificada);
            
            JOptionPane.showMessageDialog(this, "Instalacion modificada con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
   
            Limpiar();
            txtCodins.setEnabled(true); 
            actulizarTabla();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar la modificación: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnModificarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton checkAlta;
    private javax.swing.JRadioButton checkBaja;
    private javax.swing.JCheckBox chkEstadoins;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelIns1;
    private javax.swing.JLabel labelTrat10;
    private javax.swing.JLabel labelins2;
    private javax.swing.JLabel labelins3;
    private javax.swing.JLabel labelins5;
    private javax.swing.JLabel labelins7;
    private javax.swing.JTextField txtCodins;
    private javax.swing.JTextField txtCostoins;
    private javax.swing.JTextField txtDetalleins;
    private javax.swing.JTextField txtNombreins;
    // End of variables declaration//GEN-END:variables
}
