/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.DiaDeSpa;
import Persistencia.DiaDeSpaData;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ema
 */
public class VistaDiaSpasDados extends javax.swing.JPanel {

    /**
     * Creates new form VistaDiaSpasDados
     */
    menu menu;
    DiaDeSpaData data;
    
    public VistaDiaSpasDados(menu menu) {
        initComponents();
        this.menu = menu;
        data = new DiaDeSpaData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableVista = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        TableVista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableVista);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Dia De Spa Datos");

        jButton1.setText("SALIR");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setEnabled(false);
        this.setVisible(false);
        menu.activarTodosLosBotones();
    }//GEN-LAST:event_jButton1ActionPerformed


    public void mostrarDiasDeSpa() {
    DiaDeSpa[] diasdespa = data.obtenerDiasDeSpa();

    // Crear el modelo de tabla
    DefaultTableModel dataModel = new DefaultTableModel();

    // columnas
    dataModel.addColumn("CodPack");
    dataModel.addColumn("Fecha y Hora");
    dataModel.addColumn("Preferencias");
    dataModel.addColumn("CodCliente");
    dataModel.addColumn("Estado");
    dataModel.addColumn("EstadoPago");

    // Llenar la tabla con un for
    for (int i = 0; i < diasdespa.length; i++) {
        DiaDeSpa d = diasdespa[i];

        Object[] fila = new Object[6];
        fila[0] = d.getCodPack();
        fila[1] = d.getFechaHora();  
        fila[2] = d.getPreferencia();
        fila[3] = d.getCodCliente();
        fila[4] = d.isEstado();
        fila[5] = d.isEstadoPago();

        dataModel.addRow(fila);
    }

    // Setear el modelo a la tabla
    TableVista.setModel(dataModel);
}

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableVista;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
