
package Vista;

import Modelo.Consultorio;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Persistencia.ConsultorioData;
import java.util.Arrays;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JButton;



public class VistaConsultorio extends javax.swing.JPanel {

   ConsultorioData consultorio;
   String[] usos = new String[0];
   String[] equipamiento = new String[0];
   menu men;
   
    public VistaConsultorio(menu men) {
        initComponents();
        //enlazar con clases para usar metodos guardar y borrar y controlar botones
        this.men = men;
        consultorio = new ConsultorioData();
        
        //actualizar la info apenas se abre
        actualizarArreglo();
        desactivarCodigo();
        actualizarListas();      
        
        //para no tener todo activado
        buscar.setEnabled(false);
        tfbuscar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        grupobotones = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfbuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaequipamiento = new javax.swing.JTable();
        apto = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        crear = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablausos = new javax.swing.JTable();
        agregarusos = new javax.swing.JButton();
        agregarequip = new javax.swing.JButton();
        jtequi = new javax.swing.JTextField();
        jtagre = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        consultorios = new javax.swing.JTable();
        buscar = new javax.swing.JButton();
        radiobuscar = new javax.swing.JRadioButton();
        radiocrear = new javax.swing.JRadioButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Vista Consultorio");

        jLabel2.setText("Numero De Consultorio");

        tfbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfbuscarActionPerformed(evt);
            }
        });

        tablaequipamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Equipamiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaequipamiento);

        jLabel5.setText("Apto");

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tablausos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Usos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablausos);

        agregarusos.setText("Agregar");
        agregarusos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarusosActionPerformed(evt);
            }
        });

        agregarequip.setText("Agregar");
        agregarequip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarequipActionPerformed(evt);
            }
        });

        jtequi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtequiActionPerformed(evt);
            }
        });

        jtagre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtagreActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        consultorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Consultorios"
            }
        ));
        jScrollPane4.setViewportView(consultorios);

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        grupobotones.add(radiobuscar);
        radiobuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobuscarActionPerformed(evt);
            }
        });

        grupobotones.add(radiocrear);
        radiocrear.setSelected(true);
        radiocrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiocrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tfbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(apto)
                                        .addComponent(crear))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(borrar)
                                                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(radiobuscar)
                                                .addComponent(radiocrear)))
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jtagre, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(agregarusos))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtequi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(agregarequip))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salir)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtagre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarusos)
                    .addComponent(jtequi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarequip))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscar)
                            .addComponent(radiobuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apto)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radiocrear)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(crear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void desactivarCodigo(){
    tfbuscar.setEnabled(false);
    }
    
    private void tfbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfbuscarActionPerformed

    private void jtagreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtagreActionPerformed
     
    String nuevoUso = jtagre.getText().trim();
    if (!nuevoUso.isEmpty()) {
    usos = Arrays.copyOf(usos, usos.length + 1);
    usos[usos.length - 1] = nuevoUso;
    actualizarListas();
    jtagre.setText("");
}

    }//GEN-LAST:event_jtagreActionPerformed

    private void jtequiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtequiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtequiActionPerformed

    private void agregarusosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarusosActionPerformed

        String nuevoUso = jtagre.getText();

        if (!nuevoUso.isEmpty()) {
            usos = Arrays.copyOf(usos, usos.length + 1);
            usos[usos.length - 1] = nuevoUso;
            actualizarListas();
            jtagre.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un uso válido");
        }

    }//GEN-LAST:event_agregarusosActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed

       if(!(tfbuscar.getText().trim().isEmpty())){
            
             int num = Integer.valueOf(tfbuscar.getText());
             Consultorio con = consultorio.Buscar(num);
             
             if (con != null) {
            JOptionPane.showMessageDialog(null, "Ya existe un Consultorio con ese id");
        }
       }

    }//GEN-LAST:event_buscarActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed

        if (usos.length == 0 && equipamiento.length == 0){
            JOptionPane.showMessageDialog(this, "las Tablas tienen que tener porlomenos 1 arreglo cada una para crear un consultorio");
            return;
        
        }
        //-------------------------------------------------------------------------posible error
        //----------------------------------------------------------------------------------------        
        
        //si hay numero de consultorio introducido                 
            Consultorio nuevo = new Consultorio();
            nuevo.setEquipamiento(equipamiento);
            nuevo.setUsos(usos);
            nuevo.setApto(apto.isSelected());
            consultorio.Guardar(nuevo);
            JOptionPane.showMessageDialog(null, "Consultorio creado correctamente"); 

             actualizarListas();
             actualizarArreglo(); 
    }//GEN-LAST:event_crearActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   
        // se selecciona cuál es el índice de la fila a borrar
        int fila = tablausos.getSelectedRow();
        if (fila == -1) return;

        // se crea un nuevo arreglo con una posición menos 
        if (usos.length > 0) {
            String[] nuevoUsos = new String[usos.length - 1];
            for (int i = 0, j = 0; i < usos.length; i++) {
                if (i != fila) { // solo copiamos si no es la fila borrada
                    nuevoUsos[j] = usos[i];
                    j++;
                }
            }
            usos = nuevoUsos;
        }

        // actualizar tabla
        actualizarListas();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        // se selecciona cuál es el índice de la fila a borrar
        int fila = tablaequipamiento.getSelectedRow();
        if (fila == -1) return;

        // se crea un nuevo arreglo con una posición menos 
        if (equipamiento.length > 0) {
            String[] nuevoEquip = new String[equipamiento.length - 1];
            for (int i = 0, j = 0; i < equipamiento.length; i++) {
                if (i != fila) { // solo copiamos si no es la fila borrada
                    nuevoEquip[j] = equipamiento[i];
                    j++;
                }
            }
            equipamiento = nuevoEquip;
        }

        // actualizar tabla
        actualizarListas();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void agregarequipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarequipActionPerformed

        String nuevoEq = jtequi.getText().trim();
        if (!nuevoEq.isEmpty()) {
            equipamiento = Arrays.copyOf(equipamiento, equipamiento.length + 1);
            equipamiento[equipamiento.length - 1] = nuevoEq;
            actualizarListas();
            jtequi.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un equipamiento válido");
        }
    }//GEN-LAST:event_agregarequipActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.setEnabled(false);
        this.setVisible(false);
        men.activarTodosLosBotones();
    }//GEN-LAST:event_salirActionPerformed

    private void radiocrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiocrearActionPerformed
        
        borrar.setEnabled(true);
        crear.setEnabled(true);
        apto.setEnabled(true);
        buscar.setEnabled(false);
        tfbuscar.setEnabled(false);
    }//GEN-LAST:event_radiocrearActionPerformed

    private void radiobuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobuscarActionPerformed
      
         borrar.setEnabled(false);
        crear.setEnabled(false);
        apto.setEnabled(false);
        buscar.setEnabled(true);
        tfbuscar.setEnabled(true);
        
    }//GEN-LAST:event_radiobuscarActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed

       int filaAborrar = consultorios.getSelectedRow();
       
       if(filaAborrar == -1) {return;}       
       
       consultorio.Eliminar(filaAborrar);
       
         actualizarListas();
         actualizarArreglo();    
       
    
    
    }//GEN-LAST:event_borrarActionPerformed

    
public void actualizarListas() {
    // ----- Tabla de usos -----
    DefaultTableModel modelousos = new DefaultTableModel(new Object[][]{}, new String[]{"Usos"});
    for (String uso : usos) {
        modelousos.addRow(new Object[]{uso});
    }
    tablausos.setModel(modelousos);

    // ----- Tabla de equipamiento -----
    DefaultTableModel modeloequi = new DefaultTableModel(new Object[][]{}, new String[]{"Equipamiento"});
    for (String eq : equipamiento) {
        modeloequi.addRow(new Object[]{eq});
    }
    tablaequipamiento.setModel(modeloequi);
}

public void actualizarArreglo() {
    // hacer el arreglo
    List<Consultorio> lista = consultorio.Listar();
    Consultorio[] consultoriosArreglo = new Consultorio[lista.size()];

    for (int i = 0; i < lista.size(); i++) {
        consultoriosArreglo[i] = lista.get(i);
    }

    String[] Columnas = {"ID", "Equipamiento", "Usos"}; 
    Object[][] data = new Object[consultoriosArreglo.length][3];

    for (int i = 0; i < consultoriosArreglo.length; i++) {
        Consultorio c = consultoriosArreglo[i];
        data[i][0] = c.getNroConsultorio();
        data[i][1] = String.join(", ", c.getEquipamiento());
        data[i][2] = String.join(", ", c.getUsos());
    }

    DefaultTableModel model = new DefaultTableModel(data, Columnas);
    consultorios.setModel(model);
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarequip;
    private javax.swing.JButton agregarusos;
    private javax.swing.JCheckBox apto;
    private javax.swing.JButton borrar;
    private javax.swing.JButton buscar;
    private javax.swing.JTable consultorios;
    private javax.swing.JButton crear;
    private javax.swing.ButtonGroup grupobotones;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtagre;
    private javax.swing.JTextField jtequi;
    private javax.swing.JRadioButton radiobuscar;
    private javax.swing.JRadioButton radiocrear;
    private javax.swing.JButton salir;
    private javax.swing.JTable tablaequipamiento;
    private javax.swing.JTable tablausos;
    private javax.swing.JTextField tfbuscar;
    // End of variables declaration//GEN-END:variables

}