
package Vista;

import Modelo.Consultorio;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Persistencia.ConsultorioData;
import java.util.Arrays;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author Ema
 */
public class VistaConsultorio extends javax.swing.JPanel {

   ConsultorioData consultorio;
   menu men; 
   String[] usos = new String[0];
   String[] equipamiento = new String[0];
   
   
   
   
    public VistaConsultorio() {
        initComponents();
        consultorio = new ConsultorioData();
        actualizarArreglo();
        desactivarCodigo();
        buttonGroup1.add(radio1);
        buttonGroup1.add(radio2);
        
        //desabilito todos los botones
        jtnum.setEnabled(false);
        Buscar.setEnabled(false);
        
        crear.setEnabled(false);
        borrar.setEnabled(false);
        jcapt.setEnabled(false);
        selecionar.setEnabled(false);
        actualizar.setEnabled(false);
        reset.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtnum = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaequipamiento = new javax.swing.JTable();
        jcapt = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        crear = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablausos = new javax.swing.JTable();
        agregarusos = new javax.swing.JButton();
        agregarequip = new javax.swing.JButton();
        jtequi = new javax.swing.JTextField();
        jtagre = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        consultorios = new javax.swing.JTable();
        Buscar = new javax.swing.JButton();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        actualizar = new javax.swing.JButton();
        selecionar = new javax.swing.JButton();
        reset = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setForeground(new java.awt.Color(153, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Vista Consultorio");

        jLabel2.setText("Numero De Consultorio");

        jtnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnumActionPerformed(evt);
            }
        });

        tablaequipamiento.setForeground(new java.awt.Color(255, 51, 0));
        tablaequipamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Equipamiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaequipamiento);

        jLabel5.setText("Apto");

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tablausos.setForeground(new java.awt.Color(255, 51, 0));
        tablausos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Usos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablausos);

        agregarusos.setText("Agregar");
        agregarusos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarusosActionPerformed(evt);
            }
        });

        agregarequip.setText("Agregar");
        agregarequip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarequipActionPerformed(evt);
            }
        });

        jtequi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtequiActionPerformed(evt);
            }
        });

        jtagre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtagreActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        consultorios.setBackground(new java.awt.Color(255, 204, 204));
        consultorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Consultorios"
            }
        ));
        jScrollPane4.setViewportView(consultorios);

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        radio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1ActionPerformed(evt);
            }
        });

        radio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio2ActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        selecionar.setText("Selecionar");
        selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(232, 232, 232)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jcapt, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jtnum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(10, 10, 10))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(58, 58, 58)
                                            .addComponent(selecionar)
                                            .addGap(18, 18, Short.MAX_VALUE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(crear, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(radio2))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(radio1))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(jLabel5))
                                        .addComponent(actualizar))
                                    .addGap(25, 25, 25)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jtagre, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(agregarusos))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtequi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(agregarequip))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salir)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtagre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarusos)
                            .addComponent(jtequi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarequip))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jtnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Buscar))
                                    .addComponent(radio1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jcapt))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(crear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radio2)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(selecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void desactivarCodigo(){
    jtnum.setEnabled(false);
    }
    
    private void jtnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtnumActionPerformed

    private void jtagreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtagreActionPerformed
     
    String nuevoUso = jtagre.getText().trim();
    //el contrario de is empty = !isempty es igual a , si no esta vacio
    if (!nuevoUso.isEmpty()) {
    
    //copyOf sirve para copiar exactamente el mismo arreglo pero cambiandole el tamaño en la segunda columna    
    usos = Arrays.copyOf(usos, usos.length + 1);
    
    //se inserta en la ultima posicion el nuevo uso
    usos[usos.length - 1] = nuevoUso;
    actualizarListas();
    jtagre.setText("");
}
    //#chequeado#
    }//GEN-LAST:event_jtagreActionPerformed

    private void jtequiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtequiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtequiActionPerformed

    private void agregarusosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarusosActionPerformed

        String nuevoUso = jtagre.getText();

        if (!nuevoUso.isEmpty()) {
            usos = Arrays.copyOf(usos, usos.length + 1);
            usos[usos.length - 1] = nuevoUso;
            actualizarListas();
            jtagre.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un uso válido");
        }

        //#chequeado#
    }//GEN-LAST:event_agregarusosActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed

     if (!jtnum.getText().trim().isEmpty()) {

        int numABuscar = Integer.valueOf(jtnum.getText().trim());
        Consultorio consul = consultorio.Buscar(numABuscar);

        if (consul == null) {
            JOptionPane.showMessageDialog(this, "No existe un consultorio con ese ID");
            return;
        }

        //equipamiento
        String[] eqApoyo = consul.getEquipamiento();
        String[][] equipamientoBuscar = new String[eqApoyo.length][1];
        for (int f = 0; f < eqApoyo.length; f++) {
            equipamientoBuscar[f][0] = eqApoyo[f];
        }
        String[] equipCols = {"Equipamiento"};
        DefaultTableModel eq = new DefaultTableModel(equipamientoBuscar, equipCols);
        tablaequipamiento.setModel(eq);

        //usos
        String[] usosApoyo = consul.getUsos();
        String[][] usosBuscar = new String[usosApoyo.length][1];
        for (int f = 0; f < usosApoyo.length; f++) {
            usosBuscar[f][0] = usosApoyo[f];
        }
        String[] usosCols = {"Usos"};
        DefaultTableModel us = new DefaultTableModel(usosBuscar, usosCols);
        tablausos.setModel(us);

    } else {
        JOptionPane.showMessageDialog(this, " No ha introducido un ID a buscar ");
    }
       
    }//GEN-LAST:event_BuscarActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed


         int filaAborrar = consultorios.getSelectedRow();
        if (filaAborrar == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila para eliminar.");
            return;
        }

        //las columnas de la tabla empiezan en el cero
        int aBorrar = (int) consultorios.getValueAt(filaAborrar, 0);

        System.out.println("ID a borrar: " + aBorrar);

        consultorio.Eliminar(aBorrar);
        
        actualizarArreglo();
        actualizarListas();

    }//GEN-LAST:event_borrarActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
    
        // se usan los arreglos para ver que no esten vacios    
        if (usos.length < 1 || equipamiento.length < 1) {
            return;
        }

        //crear un nuevo objeto para guardar
        Consultorio nuevo = new Consultorio();
        nuevo.setEquipamiento(equipamiento);
        nuevo.setUsos(usos);
        nuevo.setApto(jcapt.isSelected());

        try {
            // Guardar — se asume que la capa de persistencia asigna el ID automáticamente
            consultorio.Guardar(nuevo);
            JOptionPane.showMessageDialog(null, "Consultorio creado correctamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar el consultorio: " );
            return;
        }

        usos = new String[0];
        equipamiento = new String[0];
        actualizarListas();
        actualizarArreglo();
       

    }//GEN-LAST:event_crearActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        //se obtiene el indice con get selected row (int)
        int fila = tablausos.getSelectedRow();

        // si no seleciono fila retorna (termina la funcion)
        if (fila == -1) {
            return;
        }
        //se obtiene el modelo usado
        DefaultTableModel model = (DefaultTableModel)tablausos.getModel();
        //se remove por medio del modelo
        model.removeRow(fila);

        tablausos.setModel(model);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int fila = tablaequipamiento.getSelectedRow();

        // si no hay fila seleccionada, salir del método
        if (fila == -1) {
            return;
        }

        // obtener el modelo actual
        DefaultTableModel model = (DefaultTableModel) tablaequipamiento.getModel();

        // eliminar la fila seleccionada
        model.removeRow(fila);

        tablausos.setModel(model);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void agregarequipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarequipActionPerformed

        String nuevoEq = jtequi.getText().trim();
        if (!nuevoEq.isEmpty()) {
            equipamiento = Arrays.copyOf(equipamiento, equipamiento.length + 1);
            equipamiento[equipamiento.length - 1] = nuevoEq;
            actualizarListas();
            jtequi.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un equipamiento válido");
        }
    }//GEN-LAST:event_agregarequipActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.setEnabled(false);
        this.setVisible(false);
    }//GEN-LAST:event_salirActionPerformed

    private void radio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1ActionPerformed
     
        jtnum.setEnabled(true);
        Buscar.setEnabled(true);
        
        crear.setEnabled(false);
        borrar.setEnabled(false);
        jcapt.setEnabled(false);
        selecionar.setEnabled(false);
        actualizar.setEnabled(false);
                 
        reset.setEnabled(false);
    }//GEN-LAST:event_radio1ActionPerformed

    private void radio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio2ActionPerformed
       
        jtnum.setEnabled(false);
        Buscar.setEnabled(false);    
        
        jcapt.setEnabled(true);
        crear.setEnabled(true);
        borrar.setEnabled(true);
        selecionar.setEnabled(true);
        actualizar.setEnabled(true);            
        reset.setEnabled(true);
        
    }//GEN-LAST:event_radio2ActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed

     if(!jtnum.getText().trim().isEmpty()){
     
        
     //creo un consultorio
     String texto = jtnum.getText();
     
     Consultorio con = new Consultorio();
     con.setEquipamiento(equipamiento);
     con.setUsos(usos);
     con.setApto(jcapt.isSelected());
     con.setNroConsultorio(Integer.valueOf(texto));
     //lo guardo
     consultorio.Modificar(con);
     } 
     else{
         JOptionPane.showMessageDialog(this, "No Hay id (Hay que usar Selecionar)");
     }
    }//GEN-LAST:event_actualizarActionPerformed

    private void selecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarActionPerformed

    if(consultorios.getSelectedRow() == -1){
        JOptionPane.showMessageDialog(this, "no se ha selecionado fila a borrar");
        return;       
    }    
         //activo los metodos    
    jtnum.setEnabled(true);
    Buscar.setEnabled(true);
        
     //obtengo la fila selecionada   
     int fila =  consultorios.getSelectedRow();
     
      int num = (int) consultorios.getValueAt(fila, 0);
     
     //le seteo al campo buscar text field ese numero
     jtnum.setText(String.valueOf(num));
     BuscarActionPerformed(null);
     
      //Vuelvo a desactivar    
    jtnum.setEnabled(true);
    Buscar.setEnabled(true);   
        
     actualizarArreglo();
     actualizarListas();
    }//GEN-LAST:event_selecionarActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
    
        jtnum.setText("");
        tablausos.setModel(new DefaultTableModel());
        tablaequipamiento.setModel((new DefaultTableModel()));
        
        
        //desabilito todos los botones
        jtnum.setEnabled(false);
        Buscar.setEnabled(false);
        
        crear.setEnabled(false);
        borrar.setEnabled(false);
        jcapt.setEnabled(false);
        selecionar.setEnabled(false);
        actualizar.setEnabled(false);
        reset.setEnabled(false);
        
    }//GEN-LAST:event_resetActionPerformed

    
public void actualizarListas() {
    // ----- Tabla de usos -----
    DefaultTableModel modelousos = new DefaultTableModel(new Object[][]{}, new String[]{"Usos"});
    for (String uso : usos) {
        modelousos.addRow(new Object[]{uso});
    }
    tablausos.setModel(modelousos);

    // ----- Tabla de equipamiento -----
    DefaultTableModel modeloequi = new DefaultTableModel(new Object[][]{}, new String[]{"Equipamiento"});
    for (String eq : equipamiento) {
        modeloequi.addRow(new Object[]{eq});
    }
    tablaequipamiento.setModel(modeloequi);
}

public void actualizarArreglo() {
    //hacer el arreglo
    List<Consultorio> lista = consultorio.Listar();
    
    if(!lista.isEmpty()){
    
    Consultorio[] consultoriosArreglo = new Consultorio[lista.size()];
    
    //poner los elementos en el arreglo
    for (int i = 0; i < lista.size(); i++) {
        consultoriosArreglo[i] = lista.get(i);
    }
    
    //columnas para el table
    String[] Columnas = {"ID", "Equipamiento", "Usos"}; 
    
    // Create data for the table
    Object[][] data = new Object[consultoriosArreglo.length][];
    for (int i = 0; i < consultoriosArreglo.length; i++) {
        Consultorio c = consultoriosArreglo[i];
        
        data[i] = new Object[]{
        c.getNroConsultorio(),
        String.join(", ", c.getEquipamiento()),
        String.join(", ", c.getUsos())
        };
    
    DefaultTableModel model = new DefaultTableModel(data, Columnas);
    
    // Apply the model to your JTable
    consultorios.setModel(model); // Replace with your actual JTable variable name
}
    }
    else{
    consultorios.setModel(new DefaultTableModel());
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton actualizar;
    private javax.swing.JButton agregarequip;
    private javax.swing.JButton agregarusos;
    private javax.swing.JButton borrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable consultorios;
    private javax.swing.JButton crear;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBox jcapt;
    private javax.swing.JTextField jtagre;
    private javax.swing.JTextField jtequi;
    private javax.swing.JTextField jtnum;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JButton reset;
    private javax.swing.JButton salir;
    private javax.swing.JButton selecionar;
    private javax.swing.JTable tablaequipamiento;
    private javax.swing.JTable tablausos;
    // End of variables declaration//GEN-END:variables

}